//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModasCentroMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int ID_Producto { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Codigo_Producto { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public string Estampado { get; set; }
        public decimal Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> disponibilidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
    }
}
